apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-argo
  namespace: pipeline-prj
spec:
  params: 
    - name: APP_NAME_ARGO
      type: string
      default: my-app-argo
    - name: GIT_REPO_CONFIG
      type: string
      default: 'https://github.com/ricardoaraujo75/app-helloworld-config.git'
    - name: PROJECT_NAME
      type: string
      default: pipeline-prj
    - name: ENVIRONMENT
      type: string
      default: main
  tasks:
    - name: create-app-argocd
      params:
      - name: APP_NAME_ARGO
        value: $(params.APP_NAME_ARGO)
      - name: GIT_REPO_CONFIG
        value: $(params.GIT_REPO_CONFIG)        
      - name: PROJECT_NAME
        value: $(params.PROJECT_NAME)
      - name: ENVIRONMENT
        value: $(params.ENVIRONMENT)        
      taskRef:
        kind: Task
        name: create-app-argocd
      workspaces:
      - name: workspace
        workspace: workspace        
  workspaces:
    - name: workspace