apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipeline.openshift.io/started-by: admin
  name: pipeline-argo-cfz0rq
  namespace: pipeline-prj
  finalizers:
    - chains.tekton.dev/pipelinerun
  labels:
    tekton.dev/pipeline: pipeline-argo
spec:
  params:
    - name: APP_NAME_ARGO
      value: my-app-argo
    - name: GIT_REPO_CONFIG
      value: 'https://github.com/ricardoaraujo75/app-helloworld-config.git'
    - name: PROJECT_NAME
      value: pipeline-prj
    - name: ENVIRONMENT
      value: main
  pipelineRef:
    name: pipeline-argo
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: gp3-csi
          volumeMode: Filesystem
        status: {}
